name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file docker/ubuntu18.04/Dockerfile.cuda.devel --tag gemfield/deepvac:10.2-cudnn7-devel-ubuntu18.04-$SHA8
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_TOKEN }}
    
    - name: Push Docker image
      run: docker push gemfield/deepvac:10.2-cudnn7-devel-ubuntu18.04-$SHA8
