name: Docker Image CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get short SHA
      id: gemfield
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - uses: actions/checkout@v2
    # - name: Build the base image
    #   run: docker build . --file docker/ubuntu20.04/Dockerfile.cuda --tag gemfield/cuda:11.0.3-cudnn8-devel-ubuntu20.04
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with:
    #     username: ${{ secrets.HUB_USERNAME }}
    #     password: ${{ secrets.HUB_TOKEN }}
    # - name: Push Docker image
    #   run: docker push gemfield/cuda
    - name: Build the deepvac devel image
     run: docker build . --file docker/ubuntu20.04/Dockerfile.deepvac --tag gemfield/deepvac:11.0.3-cudnn8-devel-ubuntu20.04
    - name: Login to DockerHub
     uses: docker/login-action@v1 
     with:
       username: ${{ secrets.HUB_USERNAME }}
       password: ${{ secrets.HUB_TOKEN }}
    - name: Push Docker image
     run: docker push gemfield/deepvac
